// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUNKS7G6bjiF_k5MAIWBGwX4rZ6GS2l2Q',
    appId: '1:154988354919:web:a5580edf65a43dbf0823c2',
    messagingSenderId: '154988354919',
    projectId: 'fitpose-44abc',
    authDomain: 'fitpose-44abc.firebaseapp.com',
    storageBucket: 'fitpose-44abc.firebasestorage.app',
    measurementId: 'G-H2NZR6GQVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_5iauGox7WMATtGQsVb03-ICpdGUL22o',
    appId: '1:154988354919:android:6583bfcfca8e8fba0823c2',
    messagingSenderId: '154988354919',
    projectId: 'fitpose-44abc',
    storageBucket: 'fitpose-44abc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU2ijrkJhOZfnExZUSRJ2Yxjbg_8ZhX3c',
    appId: '1:154988354919:ios:caf5a6df800ccc690823c2',
    messagingSenderId: '154988354919',
    projectId: 'fitpose-44abc',
    storageBucket: 'fitpose-44abc.firebasestorage.app',
    iosBundleId: 'com.example.flutterFitpose',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU2ijrkJhOZfnExZUSRJ2Yxjbg_8ZhX3c',
    appId: '1:154988354919:ios:caf5a6df800ccc690823c2',
    messagingSenderId: '154988354919',
    projectId: 'fitpose-44abc',
    storageBucket: 'fitpose-44abc.firebasestorage.app',
    iosBundleId: 'com.example.flutterFitpose',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUNKS7G6bjiF_k5MAIWBGwX4rZ6GS2l2Q',
    appId: '1:154988354919:web:e9fd91c2f47d07b60823c2',
    messagingSenderId: '154988354919',
    projectId: 'fitpose-44abc',
    authDomain: 'fitpose-44abc.firebaseapp.com',
    storageBucket: 'fitpose-44abc.firebasestorage.app',
    measurementId: 'G-3T2G40D9CY',
  );
}
